vars:
    Title: 'my example page'
    CustomCSS: 'my custom css'
    MetaDescription: 'my meta description'
    'if:AskEnabled': 1
    AskLabel: 'my ask label'
    'lang:Newer posts': 'Newer Posts'
    'lang:Older posts': 'Older Posts'
    'if:Show Archive': 1
posts:
    - { type: text, permalink: '?type=post&index=1', title: title_test1, body: test1.body }
    - { type: text, body: test2.body }
    - { type: text, title: title_test3 }
    - { type: link, url: 'http://fox21.at', name: link_name1, target: 'target="_blank"', description: 'this is my description' }
    - { type: link, url: 'http://www.fox21.at', name: link_name2 }
    - { type: link, url: 'http://www.fox21.at', name: link_name2 }
postsPerPage: 50
