vars:
    Title: 'my example page'
    CustomCSS: '<!-- my custom //-->'
    MetaDescription: 'my meta description'
    'if:Show Archive': 1
    'if:AskEnabled': 0
posts:
    - { type: text, permalink: '?type=page&index=1', title: title_test1, body: test1.body }
    - { type: text, permalink: '?type=page&index=2', body: test2.body }
    - { type: text, permalink: '?type=page&index=3', title: title_test3 }
    - { type: link, permalink: '?type=page&index=6', url: 'http://fox21.at', name: link_name1, target: 'target="_blank"', description: 'this is my description' }
    - { type: link, permalink: '?type=page&index=7', url: 'http://www.fox21.at', name: link_name2 }
postsPerPage: 50
